#!/bin/bash

set -e
set -o pipefail

########################################################################
# Load modules
module load python/3.9.9

########################################################################
# Set up running directory
cd "$(dirname "${BASH_SOURCE[0]}")" 


# Read root path
rootdir=$(realpath "./../..")
echo "$rootdir"

########################################################################
# Read multiple values and assign them to variables by parsing yaml file
cellranger_parameters=$(cat ${rootdir}/project_parameters.Config.yaml | grep 'cellranger_parameters:' | awk '{print $2}')
cellranger_parameters=${cellranger_parameters//\"/}  # Removes all double quotes
echo "$cellranger_parameters"  # Output: This is a string with quotes.

genome_name_cellranger=$(cat ${rootdir}/project_parameters.Config.yaml | grep 'genome_name_cellranger:' | awk '{print $2}')
genome_name_cellranger=${genome_name_cellranger//\"/}  # Removes all double quotes
echo "$genome_name_cellranger"  # Output: This is a string with quotes.

########################################################################
# Create directories to save output files to
module_dir=$rootdir/analyses/cellranger-analysis
echo "$module_dir"

results_dir=results
echo "$results_dir"

mkdir -p ./$results_dir/03_cellranger_count_summary
mkdir -p ./$results_dir/03_cellranger_count_summary/${cellranger_parameters}
echo "./$results_dir/03_cellranger_count_summary/${cellranger_parameters}"

########################################################################
# Run to summarize results generated by CellRanger for all libraries
python $module_dir/util/summarize_cellranger_results.py --dir=$module_dir/$results_dir/02_cellranger_count/${cellranger_parameters} \
                                                        --outdir=$module_dir/$results_dir/03_cellranger_count_summary/${cellranger_parameters}/
                                                        #--genome ${genome_name_cellranger}